updateAccountUser:
  tracing: PassThrough
  tags:
    RESOURCE: user
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-user-updateAccountUser
  description: Updates user of a specific account
  handler: controllers/update-account-user/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /update-account-user/{account_id}/{cognito_id}
        method: patch
        authorizer:
          name: ApiGatewayLambdaAuthorizer
