getEvents:
  tracing: PassThrough
  tags:
    RESOURCE: schedule
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-getEvents
  description: Get all events for an account
  handler: controllers/event/get-events/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /events/get-events/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
