//Account constants
export const CHANGE_ACCOUNTS_TAB = "CHANGE_ACCOUNTS_TAB";
export const CLOSE_ACCOUNT_OPTIONS_MODAL = "CLOSE_ACCOUNT_OPTIONS_MODAL";
export const OPEN_ACCOUNT_UPDATE_MODAL = "OPEN_ACCOUNT_UPDATE_MODAL";
export const CLOSE_ACCOUNT_UPDATE_MODAL = "CLOSE_ACCOUNT_UPDATE_MODAL";
export const UPDATE_ACCOUNT_RECORD = "UPDATE_ACCOUNT_RECORD";
export const UPDATE_PARTNER_ACCOUNT_RECORD = "UPDATE_PARTNER_ACCOUNT_RECORD";
export const CLEAR_PARTNER_CONVERSION_STATE = "CLEAR_PARTNER_CONVERSION_STATE";
export const UPDATE_LOGGEDIN_USER = "UPDATE_LOGGEDIN_USER";
export const OPEN_USER_UPDATE_MODAL = "OPEN_USER_UPDATE_MODAL";
export const CLOSE_USER_UPDATE_MODAL = "CLOSE_USER_UPDATE_MODAL";
export const UPDATE_USER_RECORD = "UPDATE_USER_RECORD";
export const GET_USER_RECORD = "GET_USER_RECORD";
export const OPEN_CREATE_ACCOUNT_MODAL = "OPEN_CREATE_ACCOUNT_MODAL";
export const CLOSE_CREATE_ACCOUNT_MODAL = "CLOSE_CREATE_ACCOUNT_MODAL";

// Tickets contacts
export const GET_TICKETS = "GET_TICKETS";
export const ADD_TICKET = "ADD_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
export const DELETE_TICKETS = "DELETE_TICKETS";
export const EDIT_TICKET = "EDIT_TICKET";
export const IS_FETCHING_TICKETS = "IS_FETCHING_TICKETS";
export const HAS_REQUESTED_TICKETS = "HAS_REQUESTED_TICKETS";
export const OPEN_TICKET_MODAL = "OPEN_TICKET_MODAL";
export const CLOSE_TICKET_MODAL = "CLOSE_TICKET_MODAL";

// Plans contacts
export const GET_USER_PLANS = "GET_USER_PLANS";
export const GET_PARTNER_PLANS = "GET_PARTNER_PLANS";
export const GET_ACTIVE_USER_PLANS = "GET_ACTIVE_USER_PLANS";
export const GET_ACTIVE_PARTNER_PLANS = "GET_ACTIVE_PARTNER_PLANS";
export const IS_FETCHING_USER_PLANS = "IS_FETCHING_USER_PLANS";
export const IS_FETCHING_PARTNER_PLANS = "IS_FETCHING_PARTNER_PLANS";
export const HAS_REQUESTED_USER_PLANS = "HAS_REQUESTED_USER_PLANS";
export const HAS_REQUESTED_PARTNER_PLANS = "HAS_REQUESTED_PARTNER_PLANS";
export const CREATE_USER_PLAN = "CREATE_USER_PLAN";
export const CREATE_PARTNER_PLAN = "CREATE_PARTNER_PLAN";
export const UPDATE_USER_PLAN = "UPDATE_USER_PLAN";
export const UPDATE_PARTNER_PLAN = "UPDATE_PARTNER_PLAN";
export const DELETE_USER_PLAN = "DELETE_USER_PLAN";
export const DELETE_PARTNER_PLAN = "DELETE_PARTNER_PLAN";
export const OPEN_CREATE_USER_PLAN_MODAL = "OPEN_CREATE_USER_PLAN_MODAL";
export const OPEN_CREATE_PARTNER_PLAN_MODAL = "OPEN_CREATE_PARTNER_PLAN_MODAL";
export const CLOSE_CREATE_USER_PLAN_MODAL = "CLOSE_CREATE_USER_PLAN_MODAL";
export const CLOSE_CREATE_PARTNER_PLAN_MODAL = "CLOSE_CREATE_PARTNER_PLAN_MODAL";
export const IS_FETCHING_ACTIVE_PARTNER_PLANS = "IS_FETCHING_ACTIVE_PARTNER_PLANS";
export const HAS_REQUESTED_ACTIVE_PARTNER_PLANS = "HAS_REQUESTED_ACTIVE_PARTNER_PLANS";
export const IS_FETCHING_ACTIVE_USER_PLANS = "IS_FETCHING_ACTIVE_USER_PLANS";
export const HAS_REQUESTED_ACTIVE_USER_PLANS = "HAS_REQUESTED_ACTIVE_USER_PLANS";

// Referral contacts
export const IS_FETCHING_REFERRALS = "IS_FETCHING_REFERRALS";
export const HAS_REQUESTED_REFERRALS = "HAS_REQUESTED_REFERRALS";
export const GET_REFERRALS = "GET_REFERRALS";
export const CREATE_REFERRAL = "CREATE_REFERRAL";
export const UPDATE_REFERRAL = "UPDATE_REFERRALS";
export const DELETE_REFERRAL = "DELETE_REFERRAL";
export const DELETE_REFERRALS = "DELETE_REFERRALS";
export const OPEN_CREATE_REFERRAL_MODAL = "OPEN_CREATE_REFERRAL_MODAL";
export const CLOSE_CREATE_REFERRAL_MODAL = "CLOSE_CREATE_REFERRAL_MODAL";

// Login constants
export const IS_LOGGING_IN = "IS_LOGGING_IN";

// Authentication constants
export const IS_LOGGED_OUT = "IS_LOGGED_OUT";
export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const IS_REGISTERED = "IS_REGISTERED";

// Navigation constants
export const LOCATION_CHANGE = "@@router/LOCATION_CHANGE";
export const TOGGLE_MOBILE_NAVIGATION_MENU = "TOGGLE_MOBILE_NAVIGATION_MENU";

// Session constants
export const SET_SESSION_ACCOUNT = "SET_SESSION_ACCOUNT";
export const CLOSE_INSTALL_PROMPT_MODAL = "CLOSE_INSTALL_PROMPT_MODAL";
export const OPEN_INSTALL_PROMPT_MODAL = "OPEN_INSTALL_PROMPT_MODAL";

// Document constants
export const GET_DOCUMENTS = "GET_DOCUMENTS";
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
export const OPEN_CREATE_DOCUMENT_MODAL = "OPEN_CREATE_DOCUMENT_MODAL";
export const CLOSE_CREATE_DOCUMENT_MODAL = "CLOSE_CREATE_DOCUMENT_MODAL";
export const IS_FETCHING_DOCUMENTS = "IS_FETCHING_DOCUMENTS";
export const HAS_FETCHED_DOCUMENTS = "HAS_FETCHED_DOCUMENTS";
export const UPDATE_DOCUMENT_USAGE = "UPDATE_DOCUMENT_USAGE";

// Signup constants
export const UPDATE_CUSTOMER_SUPPORT_SIGNUP_STATE = "UPDATE_CUSTOMER_SUPPORT_SIGNUP_STATE";
export const CLEAR_CUSTOMER_SUPPORT_SIGNUP_STATE = "CLEAR_CUSTOMER_SUPPORT_SIGNUP_STATE";
export const CLEAR_SIGNUP_STATE = "CLEAR_SIGNUP_STATE";
export const CLEAR_CLIENT_REGISTRATION = "CLEAR_CLIENT_REGISTRATION";

// Misc. constants
export const CLEAR_ALL = "CLEAR_ALL";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const IS_ACTIVE = "IS_ACTIVE";
export const IS_IDLE = "IS_IDLE";
export const USER_DID_ACTION = "USER_DID_ACTION";
export const UPDATE_APPLICATION_STATUS = "UPDATE_APPLICATION_STATUS";
export const CHANGE_SETTINGS_TAB = "CHANGE_SETTINGS_TAB";
export const CHANGE_CUSTOMER_SUPPORT_SETTINGS_TAB = "CHANGE_CUSTOMER_SUPPORT_SETTINGS_TAB";
export const CHANGE_CUSTOMER_SUPPORT_PLANS_TAB = "CHANGE_CUSTOMER_SUPPORT_PLANS_TAB";
export const OPEN_PUSH_NOTIFICATION_MODAL = "OPEN_PUSH_NOTIFICATION_MODAL";
export const CLOSE_PUSH_NOTIFICATION_MODAL ="CLOSE_PUSH_NOTIFICATION_MODAL";
export const CREATE_NEW_RELATIONSHIP = "CREATE_NEW_RELATIONSHIP";
export const CLOSE_CREATE_RELATIONSHIP_MODAL = "CLOSE_CREATE_RELATIONSHIP_MODAL";
export const OPEN_CREATE_RELATIONSHIP_MODAL = "OPEN_CREATE_RELATIONSHIP_MODAL";
export const UPDATE_SIGNUP_STATE = "UPDATE_SIGNUP_STATE";

// Notification constants
export const SET_NOTIFICATION_SETTINGS = "SET_NOTIFICATION_SETTINGS";
export const IS_FETCHING_NOTIFICATION_SETTINGS = "IS_FETCHING_NOTIFICATION_SETTINGS";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";

// Security question constants
export const GET_SECURITY_QUESTIONS = "GET_SECURITY_QUESTIONS";
export const CREATE_SECURITY_QUESTION = "CREATE_SECURITY_QUESTION";
export const UPDATE_SECURITY_QUESTION = "UPDATE_SECURITY_QUESTION";
export const DELETE_SECURITY_QUESTION = "DELETE_SECURITY_QUESTION";
export const UPDATE_SECURITY_QUESTIONS = "UPDATE_SECURITY_QUESTIONS";
export const IS_FETCHING_SECURITY_QUESTIONS = "IS_FETCHING_SECURITY_QUESTIONS";
export const OPEN_CREATE_SECURITY_QUESTON_MODAL = "OPEN_CREATE_SECURITY_QUESTON_MODAL";
export const CLOSE_CREATE_SECURITY_QUESTON_MODAL = "CLOSE_CREATE_SECURITY_QUESTON_MODAL";
export const HAS_REQUESTED_SECURITY_QUESTIONS = "HAS_REQUESTED_SECURITY_QUESTIONS";
export const OPEN_SECURITY_QUESTON_RESPONSE_MODAL = "OPEN_SECURITY_QUESTON_RESPONSE_MODAL";
export const CLOSE_SECURITY_QUESTON_RESPONSE_MODAL = "CLOSE_SECURITY_QUESTON_RESPONSE_MODAL";

// Customer Service constants
export const UPDATE_DAILY_LOGINS = "UPDATE_DAILY_LOGINS";
export const IS_FETCHING_DAILY_LOGINS = "IS_FETCHING_DAILY_LOGINS";
export const HAS_REQUESTED_DAILY_LOGINS = "HAS_REQUESTED_DAILY_LOGINS";
export const GET_ALL_ACCOUNTS = "GET_ALL_ACCOUNTS";
export const IS_FETCHING_ALL_ACCOUNTS = "IS_FETCHING_ALL_ACCOUNTS";
export const HAS_REQUESTED_ALL_ACCOUNTS = "HAS_REQUESTED_ALL_ACCOUNTS";
export const CLEAR_CUSTOMER_SUPPORT = "CLEAR_CUSTOMER_SUPPORT";
export const CHANGE_CUSTOMER_SUPPORT_ACCOUNTS_TAB = "CHANGE_CUSTOMER_SUPPORT_ACCOUNTS_TAB";
export const GET_ALL_PARTNERS = "GET_ALL_PARTNERS";
export const IS_FETCHING_ALL_PARTNERS = "IS_FETCHING_ALL_PARTNERS";
export const HAS_REQUESTED_ALL_PARTNERS = "HAS_REQUESTED_ALL_PARTNERS";
export const IS_FETCHING_ALL_TRANSACTIONS = "IS_FETCHING_ALL_TRANSACTIONS";
export const GET_ALL_ACCOUNT_TRANSACTIONS = "GET_ALL_ACCOUNT_TRANSACTIONS";
export const HAS_REQUESTED_ALL_TRANSACTIONS = "HAS_REQUESTED_ALL_TRANSACTIONS";
export const IS_FETCHING_CORE_SETTINGS = "IS_FETCHING_CORE_SETTINGS";
export const HAS_REQUESTED_CORE_SETTINGS = "HAS_REQUESTED_CORE_SETTINGS";
export const GET_CORE_SETTINGS = "GET_CORE_SETTINGS";
export const UPDATE_CORE_SETTINGS = "UPDATE_CORE_SETTINGS";
export const UPDATE_APP_VERSION = "UPDATE_APP_VERSION";
export const UPDATE_DOWNLOAD_LINK = "UPDATE_DOWNLOAD_LINK";
export const CHANGE_CUSTOMER_SUPPORT_CORE_SETTINGS_TAB = "CHANGE_CUSTOMER_SUPPORT_CORE_SETTINGS_TAB";
export const CHANGE_CUSTOMER_SUPPORT_LEADS_TAB = "CHANGE_CUSTOMER_SUPPORT_LEADS_TAB";
export const CHANGE_CUSTOMER_SUPPORT_BENEFITS_TAB = "CHANGE_CUSTOMER_SUPPORT_BENEFITS_TAB";
export const CHANGE_CUSTOMER_SUPPORT_BENEFITS_APPROVAL_TAB = "CHANGE_CUSTOMER_SUPPORT_BENEFITS_APPROVAL_TAB";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const IS_FETCHING_ALL_USERS = "IS_FETCHING_ALL_USERS";
export const HAS_REQUESTED_ALL_USERS = "HAS_REQUESTED_ALL_USERS";
export const OPEN_ADD_MEMBERSHIP_MODAL = "OPEN_ADD_MEMBERSHIP_MODAL";
export const CLOSE_ADD_MEMBERSHIP_MODAL = "CLOSE_ADD_MEMBERSHIP_MODAL";
export const ADD_MEMBERSHIP = "ADD_MEMBERSHIP";
export const GET_ALL_CS_USERS = "GET_ALL_CS_USERS";
export const ADD_USER_RECORD = "ADD_USER_RECORD";
export const IS_FETCHING_CS_USERS = "IS_FETCHING_CS_USERS";
export const HAS_REQUESTED_ALL_CS_USERS = "HAS_REQUESTED_ALL_CS_USERS";
export const UPDATE_REFRESH_STATE = "UPDATE_REFRESH_STATE";
export const IS_FETCHING_PENDING_APPROVALS = "IS_FETCHING_PENDING_APPROVALS";
export const GET_PENDING_APPROVALS = "GET_PENDING_APPROVALS";
export const HAS_REQUESTED_PENDING_APPROVALS = "HAS_REQUESTED_PENDING_APPROVALS";
export const IS_FETCHING_GROUP_APPROVALS = "IS_FETCHING_GROUP_APPROVALS";
export const GET_GROUP_APPROVALS = "GET_GROUP_APPROVALS";
export const HAS_REQUESTED_GROUP_APPROVALS = "HAS_REQUESTED_GROUP_APPROVALS";
export const GET_BENEFITS_CONFIGS = "GET_BENEFITS_CONFIGS";
export const UPDATE_BENEFITS_CONFIG = "UPDATE_BENEFITS_CONFIG";
export const IS_FETCHING_BENEFITS_CONFIGS = "IS_FETCHING_BENEFITS_CONFIGS";
export const HAS_REQUESTED_BENEFITS_CONFIGS = "HAS_REQUESTED_BENEFITS_CONFIGS";

// Product constants
export const IS_FETCHING_PRODUCTS = "IS_FETCHING_PRODUCTS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const HAS_REQUESTED_PRODUCTS = "HAS_REQUESTED_PRODUCTS";
export const OPEN_CREATE_PRODUCT_MODAL = "OPEN_CREATE_PRODUCT_MODAL";
export const CLOSE_CREATE_PRODUCT_MODAL = "CLOSE_CREATE_PRODUCT_MODAL";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

// Message constants
export const GET_MESSAGES = "GET_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const OPEN_MESSAGE = "OPEN_MESSAGE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";
export const IS_FETCHING_MESSAGES = "IS_FETCHING_MESSAGES";
export const HAS_REQUESTED_MESSAGES = "HAS_REQUESTED_MESSAGES";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_MESSAGES = "DELETE_MESSAGES";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";

// Wholesale constants
export const GET_WHOLESALERS = "GET_WHOLESALERS";
export const ADD_WHOLESALER = "ADD_WHOLESALER";
export const DELETE_WHOLESALER = "DELETE_WHOLESALER";
export const EDIT_WHOLESALER = "EDIT_WHOLESALER";
export const IS_FETCHING_WHOLESALERS = "IS_FETCHING_WHOLESALERS";
export const HAS_REQUESTED_WHOLESALERS = "HAS_REQUESTED_WHOLESALERS";
export const OPEN_WHOLESALE_MODAL = "OPEN_WHOLESALE_MODAL";
export const CLOSE_WHOLESALE_MODAL = "CLOSE_WHOLESALE_MODAL";
export const IS_FETCHING_WHOLESALE_APPROVALS = "IS_FETCHING_WHOLESALE_APPROVALS";
export const GET_WHOLESALE_APPROVALS = "GET_WHOLESALE_APPROVALS";
export const HAS_REQUESTED_WHOLESALE_APPROVALS = "HAS_REQUESTED_WHOLESALE_APPROVALS";
export const OPEN_WHOLESALE_CONNECTION_MODAL = "OPEN_WHOLESALE_CONNECTION_MODAL";
export const CLOSE_WHOLESALE_CONNECTION_MODAL = "CLOSE_WHOLESALE_CONNECTION_MODAL";

// Retail constants
export const GET_RETAILERS = "GET_RETAILERS";
export const ADD_RETAILER = "ADD_RETAILER";
export const DELETE_RETAILER = "DELETE_RETAILER";
export const EDIT_RETAILER = "EDIT_RETAILER";
export const IS_FETCHING_RETAILERS = "IS_FETCHING_RETAILERS";
export const HAS_REQUESTED_RETAILERS = "HAS_REQUESTED_RETAILERS";
export const OPEN_RETAIL_MODAL = "OPEN_RETAIL_MODAL";
export const CLOSE_RETAIL_MODAL = "CLOSE_RETAIL_MODAL";

// Agents constants
export const GET_AGENTS = "GET_AGENTS";
export const ADD_AGENT = "ADD_AGENT";
export const DELETE_AGENT = "DELETE_AGENT";
export const EDIT_AGENT = "EDIT_AGENT";
export const IS_FETCHING_AGENTS = "IS_FETCHING_AGENTS";
export const HAS_REQUESTED_AGENTS = "HAS_REQUESTED_AGENTS";
export const OPEN_AGENT_MODAL = "OPEN_AGENT_MODAL";
export const CLOSE_AGENT_MODAL = "CLOSE_AGENT_MODAL";

// Groups constants
export const GET_GROUPS = "GET_GROUPS";
export const ADD_GROUP = "ADD_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const EDIT_GROUP = "EDIT_GROUP";
export const IS_FETCHING_GROUPS = "IS_FETCHING_GROUPS";
export const HAS_REQUESTED_GROUPS = "HAS_REQUESTED_GROUPS";
export const OPEN_GROUP_MODAL = "OPEN_GROUP_MODAL";
export const CLOSE_GROUP_MODAL = "CLOSE_GROUP_MODAL";
export const OPEN_GROUP_CONNECTION_MODAL = "OPEN_GROUP_CONNECTION_MODAL";
export const CLOSE_GROUP_CONNECTION_MODAL = "CLOSE_GROUP_CONNECTION_MODAL";

// Teams constants
export const GET_TEAMS = "GET_TEAMS";
export const ADD_TEAM = "ADD_TEAM";
export const DELETE_TEAM = "DELETE_TEAM";
export const EDIT_TEAM = "EDIT_TEAM";
export const IS_FETCHING_TEAMS = "IS_FETCHING_TEAMS";
export const HAS_REQUESTED_TEAMS = "HAS_REQUESTED_TEAMS";
export const OPEN_TEAM_MODAL = "OPEN_TEAM_MODAL";
export const CLOSE_TEAM_MODAL = "CLOSE_TEAM_MODAL";

// CE constants
export const GET_CE_CONFIGS = "GET_CE_CONFIGS";
export const ADD_CE_CONFIG = "ADD_CE_CONFIG";
export const DELETE_CE_CONFIG = "DELETE_CE_CONFIG";
export const EDIT_CE_CONFIG = "EDIT_CE_CONFIG";
export const IS_FETCHING_CE_CONFIGS = "IS_FETCHING_CE_CONFIGS";
export const HAS_REQUESTED_CE_CONFIGS = "HAS_REQUESTED_CE_CONFIGS";
export const OPEN_CE_CONFIG_MODAL = "OPEN_CE_CONFIG_MODAL";
export const CLOSE_CE_CONFIG_MODAL = "CLOSE_CE_CONFIG_MODAL";
export const CHANGE_CE_TAB = "CHANGE_CE_TAB";
export const GET_CE_CREDITS = "GET_CE_CREDITS";
export const IS_FETCHING_CE_CREDITS = "IS_FETCHING_CE_CREDITS";
export const HAS_REQUESTED_CE_CREDITS = "HAS_REQUESTED_CE_CREDITS";
export const OPEN_CE_CREDIT_MODAL = "OPEN_CE_CREDIT_MODAL";
export const CLOSE_CE_CREDIT_MODAL = "CLOSE_CE_CREDIT_MODAL";
export const ADD_CE_COURSE = "ADD_CE_COURSE";
export const DELETE_CE_COURSE = "DELETE_CE_COURSE";
export const DELETE_CE_COURSES = "DELETE_CE_COURSES";
export const IS_FETCHING_CE_COURSES = "IS_FETCHING_CE_COURSES";
export const GET_CE_COURSES = "GET_CE_COURSES";
export const HAS_REQUESTED_CE_COURSES = "HAS_REQUESTED_CE_COURSES";
export const OPEN_CE_COURSE_MODAL = "OPEN_CE_COURSE_MODAL";
export const CLOSE_CE_COURSE_MODAL = "CLOSE_CE_COURSE_MODAL";
export const DELETE_CE_CONFIGS = "DELETE_CE_CONFIGS";

// Survey constants
export const GET_SURVEYS = "GET_SURVEYS";
export const GET_SESSIONS = "GET_SESSIONS";
export const CREATE_SURVEY = "CREATE_SURVEY";
export const UPDATE_SURVEY = "UPDATE_SURVEY";
export const DELETE_SURVEY = "DELETE_SURVEY";
export const DELETE_SURVEYS = "DELETE_SURVEYS";
export const UPDATE_SESSION = "UPDATE_SESSION";
export const DELETE_SESSION = "DELETE_SESSION";
export const DELETE_SESSIONS = "DELETE_SESSIONS";
export const IS_FETCHING_SURVEYS = "IS_FETCHING_SURVEYS";
export const IS_FETCHING_SESSIONS = "IS_FETCHING_SESSIONS";
export const HAS_REQUESTED_SURVEYS = "HAS_REQUESTED_SURVEYS";
export const HAS_REQUESTED_SESSIONS = "HAS_REQUESTED_SESSIONS";
export const CHANGE_SURVEY_TAB = "CHANGE_SURVEY_TAB";
export const OPEN_CREATE_SURVEY_MODAL = "OPEN_CREATE_SURVEY_MODAL";
export const CLOSE_CREATE_SURVEY_MODAL = "CLOSE_CREATE_SURVEY_MODAL";
export const OPEN_CREATE_SESSION_MODAL = "OPEN_CREATE_SESSION_MODAL";
export const CLOSE_CREATE_SESSION_MODAL = "CLOSE_CREATE_SESSION_MODAL";