getSingleUser:
  tracing: PassThrough
  tags:
    RESOURCE: user
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-user-getSingleUser
  description: Gets single user from database by ID
  handler: controllers/get-single-user/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /{cognito_id}/{account_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
