Resources:
  EmailsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: "Retain"
    Properties:
      BucketName: ${self:service}-${self:provider.stage}-email-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteContentAfter1Day
            Status: 'Enabled'
            ExpirationInDays: 1
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: "Retain"
    Properties:
      Bucket: !Ref EmailsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowSESPuts
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action: s3:PutObject
            Resource: arn:aws:s3:::${self:service}-${self:provider.stage}-email-bucket/*
            Condition:
              StringEquals:
                AWS:SourceAccount: ${self:custom.common.aws_account_id}
                AWS:SourceArn: arn:aws:ses:${self:provider.region}:${self:custom.common.aws_account_id}:receipt-rule-set/SES-receipt-ruleset:receipt-rule/${self:app}-${self:provider.stage}-SES-receipt-rule
