createSingleGroupBenefits:
  tracing: PassThrough
  tags:
    RESOURCE: benefits
  name: ${self:app}-${self:provider.stage}-createSingleGroupBenefits
  description: Create a new group record
  handler: controllers/groups/create-single-group/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - http:
        path: groups/create-single-group/{account_id}/{cognito_id}
        method: post
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
