updateSingleProvider:
  tracing: PassThrough
  tags:
    RESOURCE: provider
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-updateSingleProvider
  description: Update single provider for a specific account
  handler: controllers/provider/update-single-provider/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /providers/update-single-provider/{provider_id}/{account_id}/{cognito_id}
        method: patch
        authorizer:
          name: ApiGatewayLambdaAuthorizer
