getPGrouppprovalsCS:
  tracing: PassThrough
  tags:
    RESOURCE: account
  name: ${self:app}-${self:provider.stage}-accounts-getGroupApprovalsCS
  description: Gets all pending group benefits approvals
  handler: controllers/get-group-approvals/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /get-group-approvals/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
