deleteAccountMembershipBenefits:
  tracing: PassThrough
  tags:
    RESOURCE: membership
  name: ${self:app}-${self:provider.stage}-deleteAccountMembershipBenefits
  description: Delete a single account membership
  handler: controllers/membership/delete-account-membership/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - http:
        path: membership/delete-account-membership/{membership_id}/{account_id}/{cognito_id}
        method: delete
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
