updateSingleBeneficiaryAsset:
  tracing: PassThrough
  tags:
    RESOURCE: finance
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-updateSingleBeneficiaryAsset
  description: Update single beneficiary asset for a specific user in a specific account
  handler: controllers/finance/beneficiary-assets/update-single-beneficiary-asset/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /finance/update-single-beneficiary-asset/{id}/{account_id}/{cognito_id}
        method: patch
        authorizer:
          name: ApiGatewayLambdaAuthorizer
