createSurvey:
  tracing: PassThrough
  tags:
    RESOURCE: surveys
  name: ${self:app}-${self:provider.stage}-createSurvey
  description: Create a survey
  handler: controllers/survey/create-survey/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /survey/create-survey/{account_id}/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer
