getVisitorToken:
  tracing: PassThrough
  tags:
    RESOURCE: hubspot
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-getVisitorToken
  description: Get a Hubspot visitor token for a user
  handler: controllers/hubspot/get-visitor-token/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /hubspot/get-visitor-token/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer