createClientAccountCS:
  tracing: PassThrough
  tags:
    RESOURCE: account
  name: ${self:app}-${self:provider.stage}-accounts-createClientAccountCS
  description: Creates a new client account
  handler: controllers/create-client-account/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /create-client-account/{account_id}/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer
