getActivePartnerPlans:
  tracing: PassThrough
  tags:
    RESOURCE: plan
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-getActivePartnerPlans
  description: Get all active partner plans
  handler: controllers/plan/get-active-partner-plans/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /plans/get-active-partner-plans
        method: get
