createAccountCS:
  tracing: PassThrough
  tags:
    RESOURCE: account
  name: ${self:app}-${self:provider.stage}-accounts-createAccountCS
  description: Creates a new account in the database
  handler: controllers/create-account/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /create/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer
