createSingleBudget:
  tracing: PassThrough
  tags:
    RESOURCE: finance
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-createSingleBudget
  description: Create single budget for a specific user in a specific account
  handler: controllers/finance/budgets/create-single-budget/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /finance/create-single-budget/{account_id}/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer
