getAllClientConfigsCS:
  tracing: PassThrough
  tags:
    RESOURCE: account
  name: ${self:app}-${self:provider.stage}-accounts-getAllClientConfigsCS
  description: Gets all benefits client configs
  handler: controllers/get-all-client-configs/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /get-all-client-configs/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
