createAccount:
  tracing: PassThrough
  tags:
    RESOURCE: account
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-createAccount
  description: Creates a new account in the database
  handler: controllers/account/create-account/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /accounts/create/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer
