getAccountRequest:
  tracing: PassThrough
  tags:
    RESOURCE: zendesk
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-getAccountRequest
  description: Get single zendesk request ticket for a specific account
  handler: controllers/zendesk/get-account-request/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /zendesk/get-account-request/{account_id}/{cognito_id}/{ticket_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
