createNewUserBenefits:
  tracing: PassThrough
  tags:
    RESOURCE: user
  name: ${self:app}-${self:provider.stage}-createNewUserBenefits
  description: Creates a new user in cognito and database
  handler: controllers/clients/create-new-user/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - http:
        path: clients/create-new-user/{account_id}/{cognito_id}
        method: post
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
