updateSingleUserBenefits:
  tracing: PassThrough
  tags:
    RESOURCE: user
  name: ${self:app}-${self:provider.stage}-updateSingleUserBenefits
  description: Updates single user from database by ID
  handler: controllers/user/update-single-user/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - http:
        path: users/update/{account_id}/{cognito_id}
        method: patch
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
