createUserPlanCS:
  tracing: PassThrough
  tags:
    RESOURCE: plan
  name: ${self:app}-${self:provider.stage}-createUserPlanCS
  description: Create a new plan record for users
  handler: controllers/plan/create-user-plan/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /plans/create-user-plan/{account_id}/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer
