getPartnerResponse:
  tracing: PassThrough
  tags:
    RESOURCE: partner
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-getPartnerResponse
  description: Get single response for a specific partner account
  handler: controllers/partner/get-partner-response/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /partners/get-partner-response/{quiz_id}/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
