getMessagesCS:
  tracing: PassThrough
  tags:
    RESOURCE: message
  name: ${self:app}-${self:provider.stage}-getMessagesCS
  description: Get messages sent by an account
  handler: controllers/message/get-messages/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /messages/get-messages/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
