createSingleDocumentBenefits:
  tracing: PassThrough
  tags:
    RESOURCE: document
  name: ${self:app}-${self:provider.stage}-createSingleDocumentBenefits
  description: Create single document for a specific user in a specific account
  handler: controllers/document/create-single-document/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - http:
        path: documents/create/{account_id}/{cognito_id}
        method: post
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
