getUserSettings:
  tracing: PassThrough
  tags:
    RESOURCE: user
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-user-getUserSettings
  description: Gets a specific user's settings for a specific account
  handler: controllers/get-user-settings/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /settings/notifications/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
