addUserPermissions:
  tracing: PassThrough
  tags:
    RESOURCE: permission
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-addUserPermissions
  description: Remove an array of permissions from a specific user of a specific account.
  handler: controllers/permission/add-user-permissions/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /permissions/add/{account_id}/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer
