getCustomerTransactions:
  tracing: PassThrough
  tags:
    RESOURCE: account
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-getCustomerTransactions
  description: Gets all transactions owned by a customer
  handler: controllers/account/get-customer-transactions/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /accounts/get-customer-transactions/{customer_id}/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
