updateSingleIncome:
  tracing: PassThrough
  tags:
    RESOURCE: finance
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-updateSingleIncome
  description: Update single income for a specific user in a specific account
  handler: controllers/finance/income/update-single-income/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /finance/update-single-income/{id}/{account_id}/{cognito_id}
        method: patch
        authorizer:
          name: ApiGatewayLambdaAuthorizer
