updateCEConfigCS:
  tracing: PassThrough
  tags:
    RESOURCE: ce
  name: ${self:app}-${self:provider.stage}-updateCEConfigCS
  description: Update a CE configuration
  handler: controllers/ce/update-ce-config/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /ce/update-ce-config/{config_id}/{account_id}/{cognito_id}
        method: patch
        authorizer:
          name: ApiGatewayLambdaAuthorizer
