createCECourseCS:
  tracing: PassThrough
  tags:
    RESOURCE: ce
  name: ${self:app}-${self:provider.stage}-createCECourseCS
  description: Create a new CE course
  handler: controllers/ce/create-ce-course/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /ce/create-ce-course/{account_id}/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer
