getUserRecordCS:
  tracing: PassThrough
  tags:
    RESOURCE: user
  name: ${self:app}-${self:provider.stage}-accounts-getUserRecordCS
  description: Gets single user from database by Cognito ID
  handler: controllers/get-user-record/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /get-user-record/{account_id}/{cognito_id}/{target_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
