associateAccountUser:
  tracing: PassThrough
  tags:
    RESOURCE: account
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-associateAccountUser
  description: Associates a user with an account
  handler: controllers/account/associate-account-user/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /accounts/associate/{account_id}/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer
