updateAccountMembership:
  tracing: PassThrough
  tags:
    RESOURCE: membership
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-updateAccountMembership
  description: Update a single account membership
  handler: controllers/membership/update-account-membership/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /membership/update/{account_id}/{cognito_id}
        method: patch
        authorizer:
          name: ApiGatewayLambdaAuthorizer
