approveAccountMembershipBenefits:
  tracing: PassThrough
  tags:
    RESOURCE: membership
  name: ${self:app}-${self:provider.stage}-approveAccountMembershipBenefitss
  description: Approve a single account membership
  handler: controllers/membership/approve-account-membership/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - http:
        path: membership/approve-account-membership/{account_id}/{cognito_id}
        method: patch
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
