getAccountUsers:
  tracing: PassThrough
  tags:
    RESOURCE: account
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-getAccountUsers
  description: Gets all users associated with an account
  handler: controllers/account/get-account-users/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /accounts/get-account-users/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
