//Account constants
export const CHANGE_ACCOUNTS_TAB = "CHANGE_ACCOUNTS_TAB";
export const CLOSE_ACCOUNT_OPTIONS_MODAL = "CLOSE_ACCOUNT_OPTIONS_MODAL";
export const UPDATE_ACCOUNT_RECORD = "UPDATE_ACCOUNT_RECORD";

// Login constants
export const IS_LOGGING_IN = "IS_LOGGING_IN";

// Authentication constants
export const IS_LOGGED_OUT = "IS_LOGGED_OUT";
export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const IS_REGISTERED = "IS_REGISTERED";

// Navigation constants
export const LOCATION_CHANGE = "@@router/LOCATION_CHANGE";
export const TOGGLE_MOBILE_NAVIGATION_MENU = "TOGGLE_MOBILE_NAVIGATION_MENU";

// Session constants
export const SET_SESSION_ACCOUNT = "SET_SESSION_ACCOUNT";
export const CLOSE_INSTALL_PROMPT_MODAL = "CLOSE_INSTALL_PROMPT_MODAL";
export const OPEN_INSTALL_PROMPT_MODAL = "OPEN_INSTALL_PROMPT_MODAL";
export const UPDATE_SESSION = "UPDATE_SESSION";
export const UPDATE_HUBSPOT_STATE = "UPDATE_HUBSPOT_STATE";
export const OPEN_CREATE_ACCOUNT_MODAL = "OPEN_CREATE_ACCOUNT_MODAL";
export const CLOSE_CREATE_ACCOUNT_MODAL = "CLOSE_CREATE_ACCOUNT_MODAL";
export const UPDATE_ZENDESK_STATE = "UPDATE_ZENDESK_STATE";
export const OPEN_PARTNER_LOGO_MODAL = "OPEN_PARTNER_LOGO_MODAL";
export const CLOSE_PARTNER_LOGO_MODAL = "CLOSE_PARTNER_LOGO_MODAL";

// Security question constants
export const GET_SECURITY_QUESTIONS = "GET_SECURITY_QUESTIONS";
export const GET_SECURITY_QUESTION_RESPONSES = "GET_SECURITY_QUESTION_RESPONSES";
export const CREATE_SECURITY_QUESTION_RESPONSE = "CREATE_SECURITY_QUESTION_RESPONSE";
export const IS_FETCHING_SECURITY_QUESTIONS = "IS_FETCHING_SECURITY_QUESTIONS";
export const IS_FETCHING_SECURITY_RESPONSES = "IS_FETCHING_SECURITY_RESPONSES";
export const HAS_REQUESTED_SECURITY_QUESTIONS = "HAS_REQUESTED_SECURITY_QUESTIONS";
export const HAS_REQUESTED_SECURITY_QUESTION_RESPONSES = "HAS_REQUESTED_SECURITY_QUESTION_RESPONSES";

// Document constants
export const GET_DOCUMENTS = "GET_DOCUMENTS";
export const UPDATE_DOCUMENTS_VIEW = "UPDATE_DOCUMENTS_VIEW";
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
export const OPEN_CREATE_DOCUMENT_MODAL = "OPEN_CREATE_DOCUMENT_MODAL";
export const CLOSE_CREATE_DOCUMENT_MODAL = "CLOSE_CREATE_DOCUMENT_MODAL";
export const IS_FETCHING_DOCUMENTS = "IS_FETCHING_DOCUMENTS";
export const HAS_FETCHED_DOCUMENTS = "HAS_FETCHED_DOCUMENTS";
export const UPDATE_DOCUMENT_USAGE = "UPDATE_DOCUMENT_USAGE";

// Signup constants
export const UPDATE_CUSTOMER_SUPPORT_SIGNUP_STATE = "UPDATE_CUSTOMER_SUPPORT_SIGNUP_STATE";
export const CLEAR_CUSTOMER_SUPPORT_SIGNUP_STATE = "CLEAR_CUSTOMER_SUPPORT_SIGNUP_STATE";
export const CLEAR_CLIENT_REGISTRATION = "CLEAR_CLIENT_REGISTRATION";
export const UPDATE_CLIENT_REGISTRATION = "UPDATE_CLIENT_REGISTRATION";
export const BULK_UPDATE_CLIENT_REGISTRATION = "BULK_UPDATE_CLIENT_REGISTRATION";
export const CLEAR_SIGNUP_STATE = "CLEAR_SIGNUP_STATE";
export const IS_SIGNING_UP = "IS_SIGNING_UP";
export const UPDATE_SIGNUP_STATE = "UPDATE_SIGNUP_STATE";
export const UPDATE_CONTRACT_STATE = "UPDATE_CONTRACT_STATE";
export const UPDATE_REQUEST_ID = "UPDATE_REQUEST_ID";
export const UPDATE_SIGNATURE_REQUEST_ID = "UPDATE_SIGNATURE_REQUEST_ID";

// Misc. contstants
export const CLEAR_ALL = "CLEAR_ALL";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const IS_ACTIVE = "IS_ACTIVE";
export const IS_IDLE = "IS_IDLE";
export const USER_DID_ACTION = "USER_DID_ACTION";
export const UPDATE_APPLICATION_STATUS = "UPDATE_APPLICATION_STATUS";
export const CHANGE_SETTINGS_TAB = "CHANGE_SETTINGS_TAB";
export const CHANGE_FORM_SLIDE = "CHANGE_FORM_SLIDE";
export const CLEAR_MULTI_PART_FORM ="CLEAR_MULTI_PART_FORM";
export const CHANGE_STEP_COMPLETION = "CHANGE_STEP_COMPLETION";
export const IS_FETCHING_ALL = "IS_FETCHING_ALL";
export const HAS_FETCHED_ALL = "HAS_FETCHED_ALL";

// Notification constants
export const SET_NOTIFICATION_SETTINGS = "SET_NOTIFICATION_SETTINGS";
export const IS_FETCHING_NOTIFICATION_SETTINGS = "IS_FETCHING_NOTIFICATION_SETTINGS";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";

// Customer Service constants
export const IS_FETCHING_CORE_SETTINGS = "IS_FETCHING_CORE_SETTINGS";
export const HAS_REQUESTED_CORE_SETTINGS = "HAS_REQUESTED_CORE_SETTINGS";
export const GET_CORE_SETTINGS = "GET_CORE_SETTINGS";
export const UPDATE_APP_VERSION = "UPDATE_APP_VERSION";
export const UPDATE_DOWNLOAD_LINK = "UPDATE_DOWNLOAD_LINK";
export const CLEAR_CUSTOMER_SUPPORT = "CLEAR_CUSTOMER_SUPPORT";

// Message constants
export const GET_MESSAGES = "GET_MESSAGES";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const OPEN_MESSAGE = "OPEN_MESSAGE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";
export const IS_FETCHING_MESSAGES = "IS_FETCHING_MESSAGES";
export const HAS_REQUESTED_MESSAGES = "HAS_REQUESTED_MESSAGES";

// User constants
export const UPDATE_LOGGEDIN_USER = "UPDATE_LOGGEDIN_USER";
export const CREATE_NEW_RELATIONSHIP = "CREATE_NEW_RELATIONSHIP";
export const UPDATE_RELATIONSHIP = "UPDATE_RELATIONSHIP";
export const DELETE_RELATIONSHIP = "DELETE_RELATIONSHIP";
export const OPEN_CREATE_RELATIONSHIP_MODAL = "OPEN_CREATE_RELATIONSHIP_MODAL";
export const CLOSE_CREATE_RELATIONSHIP_MODAL = "CLOSE_CREATE_RELATIONSHIP_MODAL";
export const GET_RELATIONSHIPS = "GET_RELATIONSHIPS";
export const IS_FETCHING_RELATIONSHIPS = "IS_FETCHING_RELATIONSHIPS";
export const HAS_REQUESTED_RELATIONSHIPS = "HAS_REQUESTED_RELATIONSHIPS";

// Wholesale constants
export const GET_WHOLESALERS = "GET_WHOLESALERS";
export const IS_FETCHING_WHOLESALERS = "IS_FETCHING_WHOLESALERS";
export const HAS_REQUESTED_WHOLESALERS = "HAS_REQUESTED_WHOLESALERS";
export const IS_FETCHING_WHOLESALE_APPROVALS = "IS_FETCHING_WHOLESALE_APPROVALS";
export const GET_WHOLESALE_APPROVALS = "GET_WHOLESALE_APPROVALS";
export const HAS_REQUESTED_WHOLESALE_APPROVALS = "HAS_REQUESTED_WHOLESALE_APPROVALS";

// Retail constants
export const GET_RETAILERS = "GET_RETAILERS";
export const ADD_RETAILER = "ADD_RETAILER";
export const DELETE_RETAILER = "DELETE_RETAILER";
export const EDIT_RETAILER = "EDIT_RETAILER";
export const IS_FETCHING_RETAILERS = "IS_FETCHING_RETAILERS";
export const HAS_REQUESTED_RETAILERS = "HAS_REQUESTED_RETAILERS";

// Agents constants
export const GET_AGENTS = "GET_AGENTS";
export const ADD_AGENT = "ADD_AGENT";
export const DELETE_AGENT = "DELETE_AGENT";
export const EDIT_AGENT = "EDIT_AGENT";
export const IS_FETCHING_AGENTS = "IS_FETCHING_AGENTS";
export const HAS_REQUESTED_AGENTS = "HAS_REQUESTED_AGENTS";

// Groups constants
export const GET_GROUPS = "GET_GROUPS";
export const IS_FETCHING_GROUPS = "IS_FETCHING_GROUPS";
export const HAS_REQUESTED_GROUPS = "HAS_REQUESTED_GROUPS";
export const OPEN_GROUP_MODAL = "OPEN_GROUP_MODAL";
export const CLOSE_GROUP_MODAL = "CLOSE_GROUP_MODAL";
export const IS_FETCHING_GROUP_APPROVALS = "IS_FETCHING_GROUP_APPROVALS";
export const GET_GROUP_APPROVALS = "GET_GROUP_APPROVALS";
export const HAS_REQUESTED_GROUP_APPROVALS = "HAS_REQUESTED_GROUP_APPROVALS";

// Teams constants
export const GET_TEAMS = "GET_TEAMS";
export const IS_FETCHING_TEAMS = "IS_FETCHING_TEAMS";
export const HAS_REQUESTED_TEAMS = "HAS_REQUESTED_TEAMS";
export const OPEN_TEAM_MODAL = "OPEN_TEAM_MODAL";
export const CLOSE_TEAM_MODAL = "CLOSE_TEAM_MODAL";

// Clients constants
export const GET_CLIENTS = "GET_CLIENTS";
export const ADD_CLIENT = "ADD_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const IS_FETCHING_CLIENTS = "IS_FETCHING_CLIENTS";
export const HAS_REQUESTED_CLIENTS = "HAS_REQUESTED_CLIENTS";
export const OPEN_CLIENT_MODAL = "OPEN_CLIENT_MODAL";
export const CLOSE_CLIENT_MODAL = "CLOSE_CLIENT_MODAL";
export const GET_ACTIVE_USER_PLANS = "GET_ACTIVE_USER_PLANS";
export const IS_FETCHING_ACTIVE_USER_PLANS = "IS_FETCHING_ACTIVE_USER_PLANS";
export const HAS_REQUESTED_ACTIVE_USER_PLANS = "HAS_REQUESTED_ACTIVE_USER_PLANS";

// Request constants
export const HAS_REQUESTED_SERVICE_REQUESTS = "HAS_REQUESTED_SERVICE_REQUESTS";
export const IS_FETCHING_REQUESTS = "IS_FETCHING_REQUESTS";
export const GET_SERVICE_REQUESTS = "GET_SERVICE_REQUESTS";
export const UPDATE_SERVICE_REQUESTS = "UPDATE_SERVICE_REQUESTS";
export const DISPATCH_REQUEST = "DISPATCH_REQUEST";
export const OPEN_REQUEST_MODAL = "OPEN_REQUEST_MODAL";
export const CLOSE_REQUEST_MODAL = "CLOSE_REQUEST_MODAL";
export const OPEN_TICKET_MODAL = "OPEN_TICKET_MODAL";
export const CLOSE_TICKET_MODAL = "CLOSE_TICKET_MODAL";