deleteSessionsCS:
  tracing: PassThrough
  tags:
    RESOURCE: surveys
  name: ${self:app}-${self:provider.stage}-deleteSessionsCS
  description: Delete many sessions
  handler: controllers/survey/delete-sessions/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /survey/delete-sessions/{account_id}/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer
