deletePaymentSourceCS:
  tracing: PassThrough
  tags:
    RESOURCE: stripe
  name: ${self:app}-${self:provider.stage}-deletePaymentSourceCS
  description: Delete aa Stripe payment method from a customer
  handler: controllers/stripe/delete-payment-source/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /stripe/delete-payment-source/{customer_id}/{account_id}/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer