getMessages:
  tracing: PassThrough
  tags:
    RESOURCE: message
  name: ${self:app}-${self:provider.stage}-getMessages
  description: Get messages sent by an account
  handler: controllers/message/get-messages/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - http:
        path: messages/get-messages/{account_id}/{cognito_id}
        method: get
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
