getPGrouppprovalsCS:
  tracing: PassThrough
  tags:
    RESOURCE: account
  name: ${self:app}-${self:provider.stage}-getGroupApprovalsCS
  description: Gets all pending group benefits approvals
  handler: controllers/groups/get-group-approvals/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - http:
        path: groups/get-group-approvals/{group_id}/{account_id}/{cognito_id}
        method: get
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
