checkUserEmailCS:
  tracing: PassThrough
  tags:
    RESOURCE: user
  name: ${self:app}-${self:provider.stage}-checkUserEmailCS
  description: Check if a user email is in the system
  handler: controllers/user/check-user-email/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /users/check-email/{email}
        method: get
