getSingleUserCS:
  tracing: PassThrough
  tags:
    RESOURCE: user
  name: ${self:app}-${self:provider.stage}-getSingleUserCS
  description: Gets single user from database by ID
  handler: controllers/user/get-single-user/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /users/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
