sendClientInvitationCS:
  tracing: PassThrough
  tags:
    RESOURCE: partner
  name: ${self:app}-${self:provider.stage}-accounts-sendClientInvitationCS
  description: Send a benefits client an invitation to sign up
  handler: controllers/send-client-invitation/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /send-client-invitation/{account_id}/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer
