module.exports = (resource, logicalId) => {
  if (logicalId.startsWith("Create") && logicalId.endsWith("LambdaFunction")) return { destination: "LambdaFunctionCreate" };
  if (logicalId.startsWith("Get") && logicalId.endsWith("LambdaFunction")) return { destination: "LambdaFunctionGet" };
  if (logicalId.startsWith("Update") && logicalId.endsWith("LambdaFunction")) return { destination: "LambdaFunctionUpdate" };
  if (logicalId.startsWith("Delete") && logicalId.endsWith("LambdaFunction")) return { destination: "LambdaFunctionDelete" };
  if (logicalId.startsWith("Create") && logicalId.endsWith("LambdaFunctionRole")) return { destination: "LambdaFunctionRoleCreate" };
  if (logicalId.startsWith("Get") && logicalId.endsWith("LambdaFunctionRole")) return { destination: "LambdaFunctionRoleGet" };
  if (logicalId.startsWith("Update") && logicalId.endsWith("LambdaFunctionRole")) return { destination: "LambdaFunctionRoleUpdate" };
  if (logicalId.startsWith("Delete") && logicalId.endsWith("LambdaFunctionRole")) return { destination: "LambdaFunctionRoleDelete" };
  if (logicalId.includes("LambdaFunctionRole")) return { destination: "LambdaFunctionRole" };
  if (logicalId.endsWith("LambdaFunction")) return { destination: "LambdaFunction" };
  if (logicalId.includes("LambdaVersion")) return { destination: "LambdaVersion" };
  if (logicalId.startsWith("ApiGatewayResourceAccounts")) return { destination: "ApiGatewayResourceAccounts" };
  if (logicalId.startsWith("ApiGatewayResourceClients")) return { destination: "ApiGatewayResourceClients" };
  if (logicalId.startsWith("ApiGatewayResourceUsers")) return { destination: "ApiGatewayResourceUsers" };
  if (logicalId.startsWith("ApiGatewayResourceDocuments")) return { destination: "ApiGatewayResourceDocuments" };
  if (logicalId.startsWith("ApiGatewayResourceStripe")) return { destination: "ApiGatewayResourceStripe" };
  if (logicalId.startsWith("ApiGatewayResourceHelloDashsign")) return { destination: "ApiGatewayResourceHelloDashsign" };
  if (logicalId.startsWith("ApiGatewayResourceMessages")) return { destination: "ApiGatewayResourceMessages" };
  if (logicalId.startsWith("ApiGatewayResourceHubspot")) return { destination: "ApiGatewayResourceHubspot" };
  if (logicalId.startsWith("ApiGatewayResourceAgents")) return { destination: "ApiGatewayResourceAgents" };
  if (logicalId.startsWith("ApiGatewayResourceGroups")) return { destination: "ApiGatewayResourceGroups" };
  if (logicalId.startsWith("ApiGatewayResourceRetail")) return { destination: "ApiGatewayResourceRetail" };
  if (logicalId.startsWith("ApiGatewayResourceTeams")) return { destination: "ApiGatewayResourceTeams" };
  if (logicalId.startsWith("ApiGatewayResourceWholesale")) return { destination: "ApiGatewayResourceWholesale" };
  if (logicalId.startsWith("ApiGatewayMethod") && resource.Properties.HttpMethod === "GET") return { destination: "ApiGatewayMethodGET" };
  if (logicalId.startsWith("ApiGatewayMethod") && resource.Properties.HttpMethod === "POST") return { destination: "ApiGatewayMethodPOST" };
  if (logicalId.startsWith("ApiGatewayMethod") && resource.Properties.HttpMethod === "PATCH") return { destination: "ApiGatewayMethodPATCH" };
  if (logicalId.startsWith("ApiGatewayMethod") && resource.Properties.HttpMethod === "DELETE") return { destination: "ApiGatewayMethodDELETE" };
  if (logicalId.startsWith("ApiGatewayMethod") && resource.Properties.HttpMethod === "OPTIONS") return { destination: "ApiGatewayMethodOPTIONS" };
  if (logicalId.includes("LambdaPermissionApiGateway")) return { destination: "LambdaPermissionApiGateway" };
  if (logicalId.includes("CloudWatchRole")) return { destination: "CloudWatchRole" };
};