getBeneficiaryAssets:
  tracing: PassThrough
  tags:
    RESOURCE: finance
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-getBeneficiaryAssets
  description: Gets beneficiary assets for a specific account
  handler: controllers/finance/beneficiary-assets/get-beneficiary-assets/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /finance/get-beneficiary-assets/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
