getCEConfigs:
  tracing: PassThrough
  tags:
    RESOURCE: ce
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-getCEConfigs
  description: Get all CE configurations
  handler: controllers/ce/get-ce-configs/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /ce/get-ce-configs/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
