getPartnerPlansCS:
  tracing: PassThrough
  tags:
    RESOURCE: plan
  name: ${self:app}-${self:provider.stage}-getPartnerPlansCS
  description: Get all partner plans
  handler: controllers/plan/get-partner-plans/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /plans/get-partner-plans/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
