updateSinglePartner:
  tracing: PassThrough
  tags:
    RESOURCE: partner
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-updateSinglePartner
  description: Update single partner
  handler: controllers/partner/update-single-partner/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /partners/update-single-partner/{account_id}/{cognito_id}
        method: patch
        authorizer:
          name: ApiGatewayLambdaAuthorizer
