getEmbeddableSignatureLink:
  tracing: PassThrough
  tags:
    RESOURCE: hello-sign
  name: ${self:app}-${self:provider.stage}-getEmbeddableSignatureLink
  description: Get embeddable link for Hello Sign
  handler: controllers/hello-sign/get-signature-url/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - http:
        path: hello-sign/get-signature-url/{account_id}/{cognito_id}
        method: post
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
