surveyGizmoCompleteSurvey:
  tracing: PassThrough
  tags:
    RESOURCE: survey
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-surveyGizmoCompleteSurvey
  description: Mark a survey complete
  handler: controllers/survey-gizmo/webhooks/complete-survey/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /survey-gizmo/webhooks/complete-survey/{account_id}/{cognito_id}/{survey_id}
        method: get