console: false
org: hopeportalservices
app: hopetrust
service: hopetrust-${self:custom.root}
configValidationMode: ${self:custom.common.config_validation_status.${opt:stage, "default"}}
deprecationNotificationMode: warn:summary
useDotenv: true
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  kmsKeyArn: arn:aws:kms:us-east-1:${self:custom.common.aws_account_id}:key/bef141f2-57be-47f5-a7d0-689c4a945762
  region: us-east-1
  stage: ${opt:stage, self:custom.common.defaultStage}
  stackName: ${self:service}-${self:provider.stage}-cf-stack
  httpApi:
    name: ${self:service}-${self:provider.stage}-api
    disableDefaultEndpoint: true
    cors: true
    metrics: true
    authorizers:
      ApiGatewayLambdaAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl:
          !Sub
            - 'https://cognito-idp.us-east-1.amazonaws.com/${UserPoolId}'
            - UserPoolId: ${ssm:${self:custom.common.secrets_folder}/${self:provider.stage}/${self:custom.api}/user-pool-id}
        audience: ${ssm:${self:custom.common.secrets_folder}/${self:provider.stage}/${self:custom.api}/app-client-id}
  cfnRole: arn:aws:iam::${self:custom.common.aws_account_id}:role/CloudFormationFull
  memorySize: ${self:custom.common.memorySize.${self:provider.stage}, self:custom.common.memorySize.default}
  logRetentionInDays: 14
  versionFunctions: true
  timeout: 29
  tags:
    STAGE: ${opt:stage, self:custom.common.defaultStage}
    SERVICE: ${self:app}-${self:custom.root}
  deploymentBucket:
    name: ${self:service}-${self:provider.region}-deploy-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: ${self:app}-${self:custom.root}
  endpointType: REGIONAL
  logs:
    httpApi: true
  tracing:
    lambda: true
  environment: ${file(./variables.yml)}

plugins:
  - serverless-scriptable-plugin
  - serverless-prune-plugin
  - serverless-plugin-warmup
  - serverless-deployment-bucket
  - serverless-certificate-creator
  - serverless-domain-manager
  - serverless-plugin-split-stacks
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-custom-roles

custom: ${file(./custom.yml)}

functions:
  - ${file(controllers/create-user/serverless.yml)}
  - ${file(controllers/create-account-user/serverless.yml)}
  - ${file(controllers/get-single-user/serverless.yml)}
  - ${file(controllers/update-single-user/serverless.yml)}
  - ${file(controllers/update-account-user/serverless.yml)}
  - ${file(controllers/delete-single-user/serverless.yml)}
  - ${file(controllers/delete-account-user/serverless.yml)}
  - ${file(controllers/reset-user-mfa/serverless.yml)}
  - ${file(controllers/reset-user-password/serverless.yml)}
  - ${file(controllers/update-user-settings/serverless.yml)}
  - ${file(controllers/get-user-settings/serverless.yml)}
  - ${file(controllers/check-user-email/serverless.yml)}
  - ${file(controllers/check-username/serverless.yml)}
  - ${file(controllers/cancel-signup/serverless.yml)}
  - ${file(controllers/forgot-password/serverless.yml)}
