deleteMessageCS:
  tracing: PassThrough
  tags:
    RESOURCE: message
  name: ${self:app}-${self:provider.stage}-deleteMessageCS
  description: Deletes single message record
  handler: controllers/message/delete-message/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /messages/delete-message/{message_id}/{account_id}/{cognito_id}
        method: delete
        authorizer:
          name: ApiGatewayLambdaAuthorizer
