deleteBulkEvents:
  tracing: PassThrough
  tags:
    RESOURCE: schedule
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-deleteBulkEvents
  description: Delete many events
  handler: controllers/event/delete-bulk-events/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /events/delete-bulk-events/{series_id}/{account_id}/{cognito_id}
        method: delete
        authorizer:
          name: ApiGatewayLambdaAuthorizer
