approveGroupRequest:
  tracing: PassThrough
  tags:
    RESOURCE: benefits
  name: ${self:app}-${self:provider.stage}-approveGroupRequest
  description: Approve a group request
  handler: controllers/groups/approve-group-request/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /groups/approve-group-request/{request_id}/{account_id}/{cognito_id}
        method: patch
        authorizer:
          name: ApiGatewayLambdaAuthorizer
