deleteSingleBeneficiaryAsset:
  tracing: PassThrough
  tags:
    RESOURCE: finance
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-deleteSingleBeneficiaryAsset
  description: Delete single beneficiary asset from database by ID
  handler: controllers/finance/beneficiary-assets/delete-single-beneficiary-asset/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /finance/delete-single-beneficiary-asset/{id}/{account_id}/{cognito_id}
        method: patch
        authorizer:
          name: ApiGatewayLambdaAuthorizer
