createSubscriptionCS:
  tracing: PassThrough
  tags:
    RESOURCE: stripe
  name: ${self:app}-${self:provider.stage}-createSubscriptionCS
  description: Create a stripe subscription
  handler: controllers/stripe/create-subscription/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /stripe/create-subscription/{account_id}/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer