updateSingleMedication:
  tracing: PassThrough
  tags:
    RESOURCE: medication
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-updateSingleMedication
  description: Update single medication for a specific account
  handler: controllers/medication/update-single-medication/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /medications/update-single-medication/{medication_id}/{account_id}/{cognito_id}
        method: patch
        authorizer:
          name: ApiGatewayLambdaAuthorizer
