deleteSingleMYTOSimulation:
  tracing: PassThrough
  tags:
    RESOURCE: finance
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-deleteSingleMYTOSimulation
  description: Delete single myto simulation for a specific user in a specific account
  handler: controllers/finance/myto/delete-single-myto-simulation/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /finance/delete-single-myto-simulation/{id}/{account_id}/{cognito_id}
        method: delete
        authorizer:
          name: ApiGatewayLambdaAuthorizer
