resetUserPassword:
  tracing: PassThrough
  tags:
    RESOURCE: user
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-user-resetUserPassword
  description: Reset a single users password
  handler: controllers/reset-user-password/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
        - 'ses:SendEmail'
        - 'ses:SendRawEmail'
      Resource: "*"
  events:
    - httpApi:
        path: /reset-user-password/{cognito_id}/{account_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer
