getMYTOSimulations:
  tracing: PassThrough
  tags:
    RESOURCE: finance
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-getMYTOSimulations
  description: Gets myto simulations for a specific account
  handler: controllers/finance/myto/get-myto-simulations/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /finance/get-myto-simulations/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
