deleteCECourseCS:
  tracing: PassThrough
  tags:
    RESOURCE: ce
  name: ${self:app}-${self:provider.stage}-deleteCECourseCS
  description: Delete a CE course
  handler: controllers/ce/delete-ce-course/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /ce/delete-ce-course/{course_id}/{account_id}/{cognito_id}
        method: delete
        authorizer:
          name: ApiGatewayLambdaAuthorizer
