getWholesalersBenefits:
  tracing: PassThrough
  tags:
    RESOURCE: benefits
  name: ${self:app}-${self:provider.stage}-getWholesalersBenefits
  description: Get all wholesale memberships associated with a retail account
  handler: controllers/wholesale/get-wholesalers/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - http:
        path: wholesale/get-wholesalers/{account_id}/{cognito_id}
        method: post
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
