cancelSignup:
  tracing: PassThrough
  tags:
    RESOURCE: user
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-user-cancelSignup
  description: Cancel a signup before creating database records
  handler: controllers/cancel-signup/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /cancel-signup/{email}
        method: get
