updateUserRecordCS:
  tracing: PassThrough
  tags:
    RESOURCE: user
  name: ${self:app}-${self:provider.stage}-accounts-updateUserRecordCS
  description: Updates single user from database by Cognito ID
  handler: controllers/update-user-record/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /update-user-record/{account_id}/{cognito_id}/{target_id}
        method: patch
        authorizer:
          name: ApiGatewayLambdaAuthorizer
