deleteSingleAgentBenefits:
  tracing: PassThrough
  tags:
    RESOURCE: benefits
  name: ${self:app}-${self:provider.stage}-deleteSingleAgentBenefits
  description: Deletes single agent record
  handler: controllers/agents/delete-single-agent/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - http:
        path: agents/delete-single-agent/{agent_id}/{account_id}/{cognito_id}
        method: delete
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
