updateHubspotContact:
  tracing: PassThrough
  tags:
    RESOURCE: hubspot
  name: ${self:app}-${self:provider.stage}-updateHubspotContact
  description: Update a Hubspot contact
  handler: controllers/hubspot/update-hubspot-contact/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /hubspot/update-hubspot-contact/{hubspot_contact_id}
        method: patch