getProducts:
  tracing: PassThrough
  tags:
    RESOURCE: stripe
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-getProducts
  description: Get a subset of products based on query string filters
  handler: controllers/stripe/get-products/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /stripe/get-products/{account_id}/{cognito_id}
        method: get
        authorizer:
          name: ApiGatewayLambdaAuthorizer
