createPartner:
  tracing: PassThrough
  tags:
    RESOURCE: partner
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-createPartner
  description: Create a new partner
  handler: controllers/partner/create-partner/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /partners/create/{account_id}/{cognito_id}
        method: post
        authorizer:
          name: ApiGatewayLambdaAuthorizer
