deleteSingleMedication:
  tracing: PassThrough
  tags:
    RESOURCE: medication
  name: ${self:app}-${self:custom.api}-${self:provider.stage}-deleteSingleMedication
  description: Deletes single medication from database by ID
  handler: controllers/medication/delete-single-medication/index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"
  events:
    - httpApi:
        path: /medications/delete-single-medication/{medication_id}/{account_id}/{cognito_id}
        method: delete
        authorizer:
          name: ApiGatewayLambdaAuthorizer
